  data:
    image: busybox:latest
    volumes:
      - /var/local/sentry/data:/data
      - /var/local/sentry/data/var/lib/postgresql/data:/var/lib/postgresql/data
    entrypoint: /bin/echo
  nginx:
    image: nginx
    ports:
      - "9000:80"
    links:
      - sentry
    volumes:
      - "/sentry/sentry-compose/nginx.conf:/etc/nginx/nginx.conf"
    restart: always
  sentry:
    #ports:
    #  - "9000:9000"
    build: .
    links:
     - redis
     - postgres
    env_file: ./secret_env_vars
    environment:
      - SENTRY_SERVER_EMAIL=ahmed.magdy40@gmail.com
      - SENTRY_EMAIL_HOST=smtp.gmail.com
      - SENTRY_EMAIL_PORT=587
      - SENTRY_EMAIL_USER=ahmed.magdy40@gmail.com
      - SENTRY_EMAIL_USE_TLS=yes
      - POSTGRES_PASSWORD=sentryPa$$w0rd
      - POSTGRES_USER=sentry
    volumes_from:
      - data
    restart: always
  sentry.cron:
    build: .
    links:
     - redis
     - postgres
     - sentry
    env_file: ./secret_env_vars
    environment:
      - POSTGRES_PASSWORD=sentryPa$$w0rd
      - POSTGRES_USER=sentry
    volumes_from:
      - data
    restart: always
    command: sentry run cron
  sentry.worker:
    build: .
    links:
     - redis
     - postgres
     - sentry
    env_file: ./secret_env_vars
    environment:
      - POSTGRES_PASSWORD=sentryPa$$w0rd
      - POSTGRES_USER=sentry
    volumes_from:
      - data
    restart: always
    command: sentry run worker
  redis:
    image: redis:4.0
    volumes_from:
      - data
    restart: always
  postgres:
    image: postgres:9.5
    volumes_from:
      - data
    restart: always
